name: Algolia - Remove a record

on:
  repository_dispatch:
    types:
      - resource-unpublished
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Status: ${{ github.event.client_payload.status }}"
          echo "Path: ${{ github.event.client_payload.path }}"
          echo "Title: ${{ github.event.client_payload.title }}"
          echo "Description: ${{ github.event.client_payload.description }}"
          echo "Payload: ${{ github.event.client_payload }}"
